### ISSUE TITLE
Bug 

### ISSUE THREAD

**Issue by infadm** [jpwalters/OpenVBX-Plugin-SMS-Conversation#21] opened 2016-04-23 11:32 UTC
An unknown error occurred. Please contact your OpenVBX provider. Unable to complete request: http://foodtribe.com.au/vbx/anything/plugins/sms-conversation/plugin.json?_=1461411058646

when loading the SMS Conversation TAB

**Comment by robertoamoreno** [comment] 2016-04-23 18:58
Yes getting same issue

**Comment by jpwalters** [comment] 2016-04-25 03:26
After you close the error box does everything work normally?

What version of the plugin are you running?  1.0, 1.1 or 1.2?

**Comment by jpwalters** [comment] 2016-04-25 05:24
Based on the link you provided you're running OpenVBX in sub directory.  Version 1.0 had a bug that prevented it from working in a sub directory.  Therefore if that's the version you're using upgrading to a new version should fix you're issue.  

You can download the latest release here: [Latest Release](https://github.com/jpwalters/OpenVBX-Plugin-SMS-Conversation/releases)

If that doesn't resolve your problem let me know.  

Note: The only way to see the version you're running is to open the plugin.json file located in the sms-conversation plugin folder.  The path should be <OpenVBX>/plugins/sms-conversation/plugin.json

**Comment by jpwalters** [comment] 2016-04-29 04:35
This issue is now a duplicate of #25 and the good news is that we've just resolved it.

Please download the new version 1.3 for the fix.

**Closed as completed by jpwalters** 2016-04-29 04:35 UTC
Labels: bug, duplicate
